#!/bin/bash
# Helper script to scale miners and webservers
# Works with running containers - existing containers are kept running
# Automatically generates port mappings so ALL instances have ports accessible externally
# Usage: ./docker-compose.scale.sh [num_miners] [num_webservers]
# Example: ./docker-compose.scale.sh 3 2  (3 miners, 2 webservers)

set -e

NUM_MINERS=${1:-1}
NUM_WEBSERVERS=${2:-1}

# Compose wrapper: prefer `docker compose`, fall back to `docker-compose`.
compose() {
    if docker compose version >/dev/null 2>&1; then
        docker compose "$@"
    elif command -v docker-compose >/dev/null 2>&1; then
        docker-compose "$@"
    else
        echo "Error: neither 'docker compose' nor 'docker-compose' is available" >&2
        exit 1
    fi
}

# Get current counts
CURRENT_MINERS=$(compose ps -q miner 2>/dev/null | wc -l | tr -d ' ')
CURRENT_WEBSERVERS=$(compose ps -q webserver 2>/dev/null | wc -l | tr -d ' ')

echo "Current blockchain network:"
echo "  Miners: ${CURRENT_MINERS}"
echo "  Webservers: ${CURRENT_WEBSERVERS}"
echo ""
echo "Scaling to:"
echo "  Miners: ${NUM_MINERS}"
echo "  Webservers: ${NUM_WEBSERVERS}"
echo ""

# Determine if scaling up or down
if [ "${NUM_MINERS}" -gt "${CURRENT_MINERS}" ]; then
    echo "  → Scaling UP miners: ${CURRENT_MINERS} → ${NUM_MINERS}"
elif [ "${NUM_MINERS}" -lt "${CURRENT_MINERS}" ]; then
    echo "  → Scaling DOWN miners: ${CURRENT_MINERS} → ${NUM_MINERS}"
fi

if [ "${NUM_WEBSERVERS}" -gt "${CURRENT_WEBSERVERS}" ]; then
    echo "  → Scaling UP webservers: ${CURRENT_WEBSERVERS} → ${NUM_WEBSERVERS}"
elif [ "${NUM_WEBSERVERS}" -lt "${CURRENT_WEBSERVERS}" ]; then
    echo "  → Scaling DOWN webservers: ${CURRENT_WEBSERVERS} → ${NUM_WEBSERVERS}"
fi

echo ""
echo "Generating port mappings for all instances..."

# Generate port override file to ensure ALL instances have ports mapped externally
OUTPUT_FILE="docker-compose.override.yml"

cat > "${OUTPUT_FILE}" <<EOF
version: '3.8'

# Auto-generated port mappings for multiple instances
# Generated by: docker-compose.scale.sh ${NUM_MINERS} ${NUM_WEBSERVERS}
# This ensures ALL instances have ports accessible externally

services:
  miner:
    ports:
EOF

# Generate miner port mappings
for i in $(seq 1 ${NUM_MINERS}); do
    P2P_PORT=$((2001 + i - 1))
    echo "      - \"${P2P_PORT}:${P2P_PORT}\"  # Miner instance ${i}" >> "${OUTPUT_FILE}"
done

cat >> "${OUTPUT_FILE}" <<EOF

  webserver:
    ports:
EOF

# Generate webserver port mappings
for i in $(seq 1 ${NUM_WEBSERVERS}); do
    WEB_PORT=$((8080 + i - 1))
    P2P_PORT=$((2101 + i - 1))
    INTERNAL_P2P=$((2001 + i - 1))
    echo "      - \"${WEB_PORT}:${WEB_PORT}\"  # Webserver instance ${i} - Web" >> "${OUTPUT_FILE}"
    echo "      - \"${P2P_PORT}:${INTERNAL_P2P}\"  # Webserver instance ${i} - P2P" >> "${OUTPUT_FILE}"
done

echo "  ✓ Generated ${OUTPUT_FILE} with port mappings for all instances"
echo ""

# Scale services (--no-recreate prevents recreating existing containers)
# This keeps existing containers running and only adds/removes as needed
compose up -d --no-recreate --scale miner=${NUM_MINERS} --scale webserver=${NUM_WEBSERVERS}

echo ""
echo "Scaled services:"
compose ps

echo ""
echo "Port mappings (ALL instances accessible externally):"
echo "  Miners:"
for i in $(seq 1 ${NUM_MINERS}); do
    P2P_PORT=$((2001 + i - 1))
    echo "    Instance ${i}: P2P port ${P2P_PORT} → localhost:${P2P_PORT}"
done
echo "  Webservers:"
for i in $(seq 1 ${NUM_WEBSERVERS}); do
    WEB_PORT=$((8080 + i - 1))
    P2P_PORT=$((2101 + i - 1))
    echo "    Instance ${i}: Web port ${WEB_PORT} → localhost:${WEB_PORT}, P2P port ${P2P_PORT} → localhost:${P2P_PORT}"
done
echo ""
echo "✓ All instances have ports mapped and accessible externally"

