#!/bin/bash
# Generate docker-compose.override.yml with port mappings for multiple instances
# Usage: ./generate-compose-ports.sh [num_miners] [num_webservers]

set -e

NUM_MINERS=${1:-1}
NUM_WEBSERVERS=${2:-1}

OUTPUT_FILE="docker-compose.override.yml"

echo "Generating ${OUTPUT_FILE} for ${NUM_MINERS} miners and ${NUM_WEBSERVERS} webservers..."

cat > "${OUTPUT_FILE}" <<EOF
version: '3.8'

# Auto-generated port mappings for multiple instances
# Generated by: ./generate-compose-ports.sh ${NUM_MINERS} ${NUM_WEBSERVERS}

services:
  miner:
    ports:
EOF

# Generate miner port mappings
for i in $(seq 1 ${NUM_MINERS}); do
    P2P_PORT=$((2001 + i - 1))
    echo "      - \"${P2P_PORT}:${P2P_PORT}\"  # Miner instance ${i}" >> "${OUTPUT_FILE}"
done

cat >> "${OUTPUT_FILE}" <<EOF

  webserver:
    ports:
EOF

# Generate webserver port mappings
for i in $(seq 1 ${NUM_WEBSERVERS}); do
    WEB_PORT=$((8080 + i - 1))
    P2P_PORT=$((2101 + i - 1))
    INTERNAL_P2P=$((2001 + i - 1))
    echo "      - \"${WEB_PORT}:${WEB_PORT}\"  # Webserver instance ${i} - Web" >> "${OUTPUT_FILE}"
    echo "      - \"${P2P_PORT}:${INTERNAL_P2P}\"  # Webserver instance ${i} - P2P" >> "${OUTPUT_FILE}"
done

echo ""
echo "Generated ${OUTPUT_FILE}"
echo ""
echo "Port mappings:"
echo "  Miners:"
for i in $(seq 1 ${NUM_MINERS}); do
    P2P_PORT=$((2001 + i - 1))
    echo "    Instance ${i}: P2P port ${P2P_PORT}"
done
echo "  Webservers:"
for i in $(seq 1 ${NUM_WEBSERVERS}); do
    WEB_PORT=$((8080 + i - 1))
    P2P_PORT=$((2101 + i - 1))
    echo "    Instance ${i}: Web port ${WEB_PORT}, P2P port ${P2P_PORT}"
done
echo ""
echo "Now run:"
echo "  docker compose up -d --scale miner=${NUM_MINERS} --scale webserver=${NUM_WEBSERVERS}"
echo "  # (or, legacy): docker-compose up -d --scale miner=${NUM_MINERS} --scale webserver=${NUM_WEBSERVERS}"

