#!/bin/bash
# Incremental scaling script - adds one instance at a time
# Automatically updates port mappings so ALL instances have ports accessible externally
# Usage: ./scale-up.sh [service] [current_count]
# Example: ./scale-up.sh miner 2  (scales miners from 2 to 3)

set -e

SERVICE=${1:-webserver}
CURRENT_COUNT=${2:-1}
NEW_COUNT=$((CURRENT_COUNT + 1))

echo "Scaling ${SERVICE} up: ${CURRENT_COUNT} → ${NEW_COUNT}"
echo ""

# Compose wrapper: prefer `docker compose`, fall back to `docker-compose`.
compose() {
    if docker compose version >/dev/null 2>&1; then
        docker compose "$@"
    elif command -v docker-compose >/dev/null 2>&1; then
        docker-compose "$@"
    else
        echo "Error: neither 'docker compose' nor 'docker-compose' is available" >&2
        exit 1
    fi
}

# Get current counts for both services
CURRENT_MINERS=$(compose ps -q miner 2>/dev/null | wc -l | tr -d ' ')
CURRENT_WEBSERVERS=$(compose ps -q webserver 2>/dev/null | wc -l | tr -d ' ')

# Determine new counts after scaling
if [ "${SERVICE}" = "miner" ]; then
    NEW_MINERS=${NEW_COUNT}
    NEW_WEBSERVERS=${CURRENT_WEBSERVERS}
else
    NEW_MINERS=${CURRENT_MINERS}
    NEW_WEBSERVERS=${NEW_COUNT}
fi

# Generate port override file for updated counts
echo "Updating port mappings..."
OUTPUT_FILE="docker-compose.override.yml"

cat > "${OUTPUT_FILE}" <<EOF
version: '3.8'

# Auto-generated port mappings for multiple instances
# Generated by: scale-up.sh
# This ensures ALL instances have ports accessible externally

services:
  miner:
    ports:
EOF

# Generate miner port mappings
for i in $(seq 1 ${NEW_MINERS}); do
    P2P_PORT=$((2001 + i - 1))
    echo "      - \"${P2P_PORT}:${P2P_PORT}\"  # Miner instance ${i}" >> "${OUTPUT_FILE}"
done

cat >> "${OUTPUT_FILE}" <<EOF

  webserver:
    ports:
EOF

# Generate webserver port mappings
for i in $(seq 1 ${NEW_WEBSERVERS}); do
    WEB_PORT=$((8080 + i - 1))
    P2P_PORT=$((2101 + i - 1))
    INTERNAL_P2P=$((2001 + i - 1))
    echo "      - \"${WEB_PORT}:${WEB_PORT}\"  # Webserver instance ${i} - Web" >> "${OUTPUT_FILE}"
    echo "      - \"${P2P_PORT}:${INTERNAL_P2P}\"  # Webserver instance ${i} - P2P" >> "${OUTPUT_FILE}"
done

echo "  ✓ Updated ${OUTPUT_FILE}"
echo ""

# Scale up by one
compose up -d --no-recreate --scale ${SERVICE}=${NEW_COUNT}

echo ""
echo "Waiting for new container to start..."
sleep 5

echo ""
echo "Current ${SERVICE} containers:"
compose ps ${SERVICE}

echo ""
echo "Port mappings (ALL instances accessible externally):"
if [ "${SERVICE}" = "miner" ]; then
    P2P_PORT=$((2001 + NEW_COUNT - 1))
    echo "  New miner instance ${NEW_COUNT}: P2P port ${P2P_PORT} → localhost:${P2P_PORT}"
else
    WEB_PORT=$((8080 + NEW_COUNT - 1))
    P2P_PORT=$((2101 + NEW_COUNT - 1))
    echo "  New webserver instance ${NEW_COUNT}: Web port ${WEB_PORT} → localhost:${WEB_PORT}, P2P port ${P2P_PORT} → localhost:${P2P_PORT}"
fi

echo ""
echo "View logs of new container:"
echo "  docker compose logs -f ${SERVICE}_${NEW_COUNT}"

